"""A fresh, locally-generated narration the moment a cockpit attaches.

O+V is proactive. When a developer attaches to watch it work, it should
say — in its own voice, grounded in what it is actually doing right now —
what it is working on or about to do. Not the static "attached, I'm
listening" help line (that is a fixed affordance and stays): this is
generated by the LOCAL model against a live situation digest, so it
differs every attach and reflects real state.

Design
------
* **Local-first.** The prompt routes through :func:`rt_gate.gate_completion`
  with ``prefer="local"`` — the fine-tuned model on this host answers,
  never a canned string. No cloud key, no lane: no briefing (correct —
  the organism does not fabricate a greeting it cannot generate).
* **Grounded, never generic.** The situation digest (queued signals,
  active goals, recent ops, posture — the same reader registry the
  ``/btw`` aside grounds on) is fed into the prompt, so two attaches to
  two different states produce two different briefings, and an idle
  organism says what it is *watching for* rather than inventing activity.
* **Off the attach path.** Scheduled as a task from the bridge's
  ``_on_client``; a cold model (a 30B's first load) makes the briefing
  ARRIVE LATE, never makes the attach itself wait. Bounded by a timeout.
* **Non-spammy.** A process-wide minimum interval coalesces a burst of
  re-attaches (a flapping client, several panes) into one briefing.
* **Emitted as the organism's voice.** A ``NarrativeKind.INTENT`` frame
  on the default channel — the SAME surface the per-op 💭 intent uses —
  so the existing commit listener carries it to every attached cockpit
  through the transport's mirror. One producer, one renderer, one lane.

Masters / knobs (all env, no hardcoded policy):
  * ``JARVIS_ATTACH_BRIEFING_ENABLED``          (default true)
  * ``JARVIS_ATTACH_BRIEFING_MIN_INTERVAL_S``   (default 20; 0 = every attach)
  * ``JARVIS_ATTACH_BRIEFING_TIMEOUT_S``        (default 60; floor 2)
  * ``JARVIS_ATTACH_BRIEFING_MAX_TOKENS``       (default 90; floor 16)
"""
from __future__ import annotations

import asyncio
import logging
import os
import threading
import time
from typing import Optional

logger = logging.getLogger("Ouroboros.AttachBriefing")

_TRUTHY = ("1", "true", "yes", "on")
_FALSY = ("0", "false", "no", "off")

MASTER_FLAG = "JARVIS_ATTACH_BRIEFING_ENABLED"
MIN_INTERVAL_FLAG = "JARVIS_ATTACH_BRIEFING_MIN_INTERVAL_S"
TIMEOUT_FLAG = "JARVIS_ATTACH_BRIEFING_TIMEOUT_S"
MAX_TOKENS_FLAG = "JARVIS_ATTACH_BRIEFING_MAX_TOKENS"

_SYSTEM_PROMPT = (
    "You are O+V (Ouroboros + Venom), an autonomous coding organism that "
    "continuously develops its own codebase without being prompted. A "
    "developer has just attached their terminal to watch you work. In ONE or "
    "TWO sentences, first person, present tense, calm and specific, tell them "
    "what you are working on or about to do RIGHT NOW. Ground every claim in "
    "the live situation you are given — name the actual files, tests, or "
    "signals, never a placeholder. No greeting, no preamble, no lists, no "
    "meta-commentary about being an AI. If nothing is in flight, say plainly "
    "what you are watching for."
)

#: Last successful (or attempted) emission — process-wide, because the
#: question "did we just greet someone?" is about the organism, not one op.
_last_emit_monotonic: float = 0.0
_lock = threading.Lock()


def _envb(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    v = raw.strip().lower()
    if v in _TRUTHY:
        return True
    if v in _FALSY:
        return False
    return default


def _envf(name: str, default: float, floor: float) -> float:
    try:
        return max(floor, float(os.environ.get(name, str(default))))
    except (TypeError, ValueError):
        return default


def _envi(name: str, default: int, floor: int) -> int:
    try:
        return max(floor, int(str(os.environ.get(name, str(default))).strip()))
    except (TypeError, ValueError):
        return default


def enabled() -> bool:
    """Master — default ON. A local lane is still required to produce one."""
    return _envb(MASTER_FLAG, True)


def min_interval_s() -> float:
    return _envf(MIN_INTERVAL_FLAG, 20.0, 0.0)


def timeout_s() -> float:
    return _envf(TIMEOUT_FLAG, 60.0, 2.0)


def max_tokens() -> int:
    return _envi(MAX_TOKENS_FLAG, 90, 16)


async def _grounding() -> str:
    """The live-situation digest, off the loop and time-boxed. NEVER raises."""
    try:
        from backend.core.ouroboros.governance.side_channel import (
            build_grounding,
            compose_situation,
        )
        situation = await compose_situation()
        return build_grounding(situation)
    except Exception:  # noqa: BLE001 — a missing digest just means a leaner prompt
        logger.debug("[AttachBriefing] grounding unavailable", exc_info=True)
        return ""


async def _generate(grounding: str) -> str:
    """Ask the LOCAL model what it is doing right now. Returns "" on any
    failure (no lane, timeout, exhaustion) — the organism never fabricates a
    greeting it could not generate. NEVER raises."""
    prompt = (
        "Live situation (what you are actually doing right now):\n\n"
        + (grounding.strip() or "(no live activity is reported)")
        + "\n\nIn one or two grounded sentences, tell the developer who just "
        "attached what you are working on or about to do."
    )
    try:
        from backend.core.ouroboros.governance.rt_gate import (
            GateProviderExhaustedError,
            gate_completion,
        )
    except Exception:  # noqa: BLE001
        return ""
    try:
        raw = await asyncio.wait_for(
            gate_completion(
                prompt,
                caller_id="attach_briefing",
                system_prompt=_SYSTEM_PROMPT,
                max_tokens=max_tokens(),
                prefer="local",
            ),
            timeout=timeout_s(),
        )
        return (raw or "").strip()
    except asyncio.TimeoutError:
        logger.info(
            "[AttachBriefing] briefing timed out after %.0fs (model likely "
            "cold) — attach unaffected", timeout_s(),
        )
        return ""
    except GateProviderExhaustedError:
        logger.info("[AttachBriefing] no generation lane for a briefing")
        return ""
    except Exception as exc:  # noqa: BLE001
        logger.info("[AttachBriefing] briefing failed: %s", exc)
        return ""


def _emit_frame(prose: str, session: str) -> bool:
    """Publish the briefing as the organism's INTENT voice on the default
    narrative channel. The transport's commit listener carries it to every
    attached cockpit. Returns whether a frame was recorded. NEVER raises."""
    try:
        from backend.core.ouroboros.battle_test.narrative_channel import (
            NarrativeKind,
            get_default_channel,
        )
        op_id = "attach" + (f":{session}" if session else "")
        frame = get_default_channel().emit_complete(
            op_id=op_id, phase="ATTACH",
            kind=NarrativeKind.INTENT, prose=prose, provider="local",
        )
        return frame is not None
    except Exception:  # noqa: BLE001
        logger.debug("[AttachBriefing] emit failed", exc_info=True)
        return False


def _claim_slot() -> bool:
    """Reserve the min-interval window so a burst of re-attaches produces one
    briefing. Optimistic: the slot is taken BEFORE generation so two
    concurrent attaches do not both spend the model; released by
    :func:`_release_slot` if nothing was emitted."""
    global _last_emit_monotonic  # noqa: PLW0603
    now = time.monotonic()
    with _lock:
        if _last_emit_monotonic and (now - _last_emit_monotonic) < min_interval_s():
            return False
        _prev = _last_emit_monotonic
        _last_emit_monotonic = now
    # Stash the previous value on the function for a clean rollback.
    _claim_slot._prev = _prev  # type: ignore[attr-defined]
    return True


def _release_slot() -> None:
    global _last_emit_monotonic  # noqa: PLW0603
    with _lock:
        _last_emit_monotonic = getattr(_claim_slot, "_prev", 0.0)  # type: ignore[attr-defined]


async def emit_for_attach(*, session: str = "") -> bool:
    """Compose and emit ONE grounded, locally-generated briefing for a cockpit
    that just attached. Fire-and-forget from the bridge. Returns whether a
    briefing was emitted. NEVER raises — a greeting must never break an attach.
    """
    if not enabled():
        return False
    if not _claim_slot():
        return False  # coalesced into a recent briefing
    try:
        grounding = await _grounding()
        prose = await _generate(grounding)
        if not prose:
            _release_slot()  # nothing said — let the next attach try
            return False
        emitted = _emit_frame(prose, session)
        if not emitted:
            _release_slot()
        else:
            logger.info(
                "[AttachBriefing] greeted an attaching cockpit (%d chars)",
                len(prose),
            )
        return emitted
    except Exception:  # noqa: BLE001 — the whole point is to never break attach
        logger.debug("[AttachBriefing] briefing degraded", exc_info=True)
        _release_slot()
        return False


def schedule_for_attach(session: str = "") -> Optional["asyncio.Task"]:
    """Schedule :func:`emit_for_attach` on the running loop, if one is running
    and the feature is enabled. Returns the task (referenced by the caller so
    it is not garbage-collected) or ``None``. NEVER raises."""
    if not enabled():
        return None
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        return None
    try:
        return loop.create_task(emit_for_attach(session=session))
    except Exception:  # noqa: BLE001
        return None


__all__ = [
    "MASTER_FLAG",
    "emit_for_attach",
    "enabled",
    "max_tokens",
    "min_interval_s",
    "schedule_for_attach",
    "timeout_s",
]
